export enum CustomEventTypeEnum {
  NONE,
  CHARACTER_JUMP,
  CHARACTER_MOVE,
  CHARACTER_MOVE_LEFT,
  CHARACTER_MOVE_RIGHT,
  CHARACTER_ATTACK,
  CHARACTER_REVIVLE,
  CHARACTER_BUFF_HP,
}

export const CustomEventType = {
  NONE: "NONE",
  CHARACTER_JUMP: "CHARACTER_JUMP",
  CHARACTER_MOVE: "CHARACTER_MOVE",
  CHARACTER_MOVE_LEFT: "CHARACTER_MOVE_LEFT",
  CHARACTER_MOVE_RIGHT: "CHARACTER_MOVE_RIGHT",
  CHARACTER_ATTACK: "CHARACTER_ATTACK",
  CHARACTER_REVIVLE: "CHARACTER_REVIVLE",
  CHARACTER_TAKE_DAMAGE: "CHARACTER_TAKE_DAMAGE",
  CHARACTER_DIE: "CHARACTER_DIE",
  CHARACTER_BUFF_HP: "CHARACTER_BUFF_HP",
};

export enum CustomDpadEventStatus {
  START,
  MOVE,
  END,
  CANCEL,
}
