export enum CustomEventTypes {
  NONE,
  CHARACTER_JUMP,
  CHARACTER_MOVE,
  CHARACTER_MOVE_LEFT,
  CHARACTER_MOVE_RIGHT,
  CHARACTER_ATTACK,
  CHARACTER_REVIVLE,
}

export const CustomEventType = {
  NONE: "NONE",
  CHARACTER_JUMP: "CHARACTER_JUMP",
  CHARACTER_MOVE: "CHARACTER_MOVE",
  CHARACTER_MOVE_LEFT: "CHARACTER_MOVE_LEFT",
  CHARACTER_MOVE_RIGHT: "CHARACTER_MOVE_RIGHT",
  CHARACTER_ATTACK: "CHARACTER_ATTACK",
  CHARACTER_REVIVLE: "CHARACTER_REVIVLE",
};

export enum CustomEventStatus {
  START,
  MOVE,
  END,
  CANCEL,
}
